kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.db.pvc.name }}
  annotations:
      "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ $.Values.db.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
