apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.backend.name }}
spec:
  type: {{ $.Values.backend.service.type }}
  selector:
    app: {{ $.Values.backend.name }}
  ports:
  - name: backend
    protocol: TCP
    targetPort: {{ $.Values.backend.service.port }}
    port: {{ $.Values.backend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.db.service.name }}
spec:
  type: {{ $.Values.db.service.type }}
  selector:
    app: {{ $.Values.db.name }}
  ports:
  - name: database
    protocol: TCP
    targetPort: {{ $.Values.db.service.port }}
    port: {{ $.Values.db.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.db.public_service.name }}
spec:
  type: {{ $.Values.db.public_service.type }}
  selector:
    app: {{ $.Values.db.name }}
  ports:
  - name: publicdatabase
    protocol: TCP
    targetPort: {{ $.Values.db.public_service.port }}
    port: {{ $.Values.db.public_service.port }}
    nodePort: {{ $.Values.db.public_service.nodePort }}
